steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, -f, infra/n4.27s/gateway.Dockerfile, -t, us-central1-docker.pkg.dev/$PROJECT_ID/clervo-n427s-images/gateway:$BUILD_ID, .]
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/clervo-n427s-images/gateway:$BUILD_ID
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s
