/*
 * The runtime view of the identity package.
 *
 * `identity.json` is generated by scripts/site/build-identity.mjs from the one
 * geometry solver, and imported rather than re-declared so the header mark,
 * the favicon, the app icon, and the social avatar are provably the same
 * shape. Re-typing these numbers here is how a logo starts drifting.
 */

import identity from '../brand/identity.json';

export const geometry = identity.geometry;
export const palette = identity.palette;
export const clearSpace = identity.clearSpace;
export const minimumSize = identity.minimumSize;
