// Registry-to-public-output consistency.
//
// Every factual claim on a public surface must trace to packages/catalog/
// live-registry.json, which is generated by probing the deployed system. These
// tests assert that relationship. They deliberately do NOT assert any
// particular status value: a test that pins "unavailable" or "payment off" is
// what previously made honesty break the build and left the repository frozen
// and lying. Change the runtime and these tests keep passing; disagree with the
// runtime and they fail.

import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';

const root = path.resolve(import.meta.dirname, '../..');
const json = async (file) => JSON.parse(await readFile(path.join(root, file), 'utf8'));
const text = (file) => readFile(path.join(root, file), 'utf8');

const LIFECYCLE_STATES = new Set(['live', 'supply_paused', 'unavailable']);
const PROOF_LEVELS = ['none', 'quote_observed_unpaid', 'paid_outcome_verified', 'externally_repeated'];

const registry = await json('packages/catalog/live-registry.json');

test('the live registry uses exactly the three lifecycle states and four proof levels', () => {
  assert.equal(registry.schemaVersion, 'clervo.live-registry.v1');
  assert.equal(registry.handEditingProhibited, true);
  assert.deepEqual(Object.keys(registry.states).sort(), [...LIFECYCLE_STATES].sort());
  assert.deepEqual(Object.keys(registry.proofLevels).sort(), [...PROOF_LEVELS].sort());
  for (const product of registry.products) {
    assert.ok(LIFECYCLE_STATES.has(product.state), `product ${product.id} state ${product.state}`);
    assert.ok(PROOF_LEVELS.includes(product.proof), `product ${product.id} proof ${product.proof}`);
  }
  for (const route of registry.aiRoutes) {
    assert.ok(LIFECYCLE_STATES.has(route.state), `route ${route.routeId} state ${route.state}`);
    assert.ok(PROOF_LEVELS.includes(route.proof), `route ${route.routeId} proof ${route.proof}`);
  }
});

test('the prober never drops a catalogued route, and a paused route keeps its reason', async () => {
  const catalog = await json('generated/b7-ai/public/models.json');
  const catalogued = catalog.data.map(({ id }) => id).sort();
  const recorded = registry.aiRoutes.map(({ routeId }) => routeId).sort();
  // A probe failure yields supply_paused, never removal. Losing a route here
  // erases supply we own.
  assert.deepEqual(recorded, catalogued);
  for (const route of registry.aiRoutes.filter(({ state }) => state === 'supply_paused')) {
    assert.equal(typeof route.reason, 'string', `${route.routeId} must carry a pause reason`);
    assert.ok(route.reason.length > 0, `${route.routeId} pause reason must not be empty`);
  }
});

test('a route or product is only sellable where the registry says it is live', () => {
  for (const route of registry.aiRoutes) {
    assert.equal(route.sellable, route.state === 'live', `${route.routeId} sellable must follow lifecycle state`);
  }
  for (const product of registry.products) {
    // Nothing that is not live may claim a proof level above none: proof is
    // earned by the deployed system, not by intent.
    if (product.state !== 'live') assert.equal(product.proof, 'none', `${product.id} must not claim proof while not live`);
  }
});

test('no product claims a proof level above the combined live-probe and accepted paid-proof ceiling', () => {
  // The HTTP prober never sends payment. Anything above
  // quote_observed_unpaid therefore needs a separately settled proof record
  // that was accepted against the current release and current quote.
  const ceiling = PROOF_LEVELS.indexOf(registry.proofCeiling.level);
  assert.ok(ceiling >= 0);
  for (const product of registry.products) {
    assert.ok(
      PROOF_LEVELS.indexOf(product.proof) <= ceiling,
      `${product.id} claims ${product.proof}, above the probe ceiling ${registry.proofCeiling.level}`,
    );
    if (PROOF_LEVELS.indexOf(product.proof) > PROOF_LEVELS.indexOf('quote_observed_unpaid')) {
      assert.equal(product.evidence?.paidOutcome?.accepted, true, `${product.id} paid proof must be explicitly accepted`);
      assert.equal(product.evidence.paidOutcome.proofLevel, product.proof);
    }
    if (product.proof === 'externally_repeated') {
      assert.equal(product.evidence?.paidOutcome?.externallyRepeated, true, `${product.id} must not infer unrelated-customer repetition from owner funding`);
    }
  }
});

test('every generated public surface renders the registry lifecycle state for reachable families only', async () => {
  const [discovery, catalog, capabilities, status] = await Promise.all([
    json('generated/public/.well-known/clervo.json'),
    json('generated/public/catalog.json'),
    json('generated/public/capabilities.json'),
    json('generated/public/status.json'),
  ]);
  // Reachability, not grading, decides what is published. A family the registry
  // marks unreachable is absent from every surface rather than listed with the
  // reason we cannot sell it.
  const expected = registry.products
    .filter(({ publiclyReachable }) => publiclyReachable)
    .map(({ id, state }) => [id, state])
    .sort();

  for (const [name, document] of [['discovery', discovery], ['catalog', catalog], ['capabilities', capabilities], ['status', status]]) {
    const rendered = document.observedTruth.products
      .map(({ id, lifecycleState }) => [id, lifecycleState])
      .sort();
    assert.deepEqual(rendered, expected, `${name} must render the registry's reachable families`);
    assert.equal(document.observedTruth.provenance.observedAt, registry.observedAt, `${name} must cite the registry observation time`);
    // Internal source paths and the prober filename are not published.
    assert.equal(Object.hasOwn(document.observedTruth.provenance, 'source'), false, `${name} must not expose an internal source path`);
    assert.equal(Object.hasOwn(document.observedTruth.provenance, 'generatedBy'), false, `${name} must not expose the prober filename`);
  }

  for (const document of [capabilities, status]) {
    for (const product of document.products) {
      const observed = registry.products.find(({ id }) => id === product.id);
      assert.equal(product.lifecycleState, observed.state);
      assert.equal(observed.publiclyReachable, true, `${product.id} must be reachable to be published`);
      assert.equal(Object.hasOwn(product, 'proofLevel'), false, `${product.id} must not carry a proof level`);
    }
  }
});

test('llms.txt lists every reachable product as available and publishes no proof level', async () => {
  const llms = await text('generated/public/llms.txt');
  for (const product of registry.products) {
    const row = llms.split('\n').find((line) => line.startsWith(`| ${product.label} |`));
    if (!product.publiclyReachable) {
      assert.equal(row, undefined, `llms.txt must not list unoffered family ${product.label}`);
      continue;
    }
    assert.ok(row !== undefined, `llms.txt must list ${product.label}`);
    assert.ok(row.includes('available'), `${product.label} row must state it is available`);
    assert.ok(!row.includes(product.proof), `${product.label} row must not publish a proof level`);
  }
});

test('public status publishes every open conformance defect and every paused route', async () => {
  const status = await json('generated/public/status.json');
  assert.deepEqual(
    status.conformanceDefectsOpen.map(({ id }) => id).sort(),
    registry.conformance.filter(({ conformant }) => !conformant).map(({ id }) => id).sort(),
  );
  // Paused supply stays visible with its reason. Hiding it would erase supply
  // we own and would make the catalog look smaller than it is.
  assert.deepEqual(
    status.aiRoutes.paused.map(({ modelId }) => modelId).sort(),
    registry.aiRoutes.filter(({ state }) => state === 'supply_paused').map(({ routeId }) => routeId).sort(),
  );
  assert.deepEqual(status.aiRoutes.counts, registry.summary.aiRoutes);
});

test('no public surface offers an operation the registry does not serve', async () => {
  const [discovery, openapi] = await Promise.all([
    json('generated/public/.well-known/clervo.json'),
    json('generated/public/openapi.json'),
  ]);
  const servedFamilies = new Set(registry.products.filter(({ state }) => state === 'live').map(({ id }) => id));
  const familyOfPath = {
    '/v1/search/free': 'search',
    '/v1/search/paid': 'search',
    '/v1/ai/execute': 'ai',
    '/v1/sandbox/execute': 'sandbox',
    '/v1/rpc/execute': 'rpc',
    '/v1/prediction/execute': 'prediction',
    '/v1/crypto/execute': 'crypto_intelligence',
  };
  for (const route of Object.keys(openapi.paths)) {
    const family = familyOfPath[route];
    if (family === undefined) continue;
    assert.ok(servedFamilies.has(family), `openapi offers ${route} but the registry does not serve ${family}`);
  }
  for (const product of discovery.products.filter(({ publicAvailable }) => publicAvailable)) {
    const paid = product.routes?.paidChallenge;
    if (paid === undefined) continue;
    assert.ok(servedFamilies.has(familyOfPath[paid]), `discovery offers ${paid} but the registry does not serve it`);
  }
});

test('the site projection is byte-identical to the generated output', async () => {
  const files = [
    'llms.txt',
    'skill.md',
    'agent.md',
    'models.json',
    'catalog.json',
    'capabilities.json',
    'pricing.json',
    'status.json',
    'onboarding.json',
    'openapi.json',
    'openapi.yaml',
    '.well-known/clervo.json',
    '.well-known/mcp.json',
    '.well-known/x402.json',
  ];
  for (const file of files) {
    const [generated, projected] = await Promise.all([
      readFile(path.join(root, 'generated/public', file)),
      readFile(path.join(root, 'apps/site/public', file)),
    ]);
    assert.ok(generated.equals(projected), `apps/site/public/${file} must equal generated/public/${file}`);
  }
});

test('the agent-facing documents render the registry rather than a hand-written claim', async () => {
  const [skill, agent, llms] = await Promise.all([
    text('generated/public/skill.md'),
    text('generated/public/agent.md'),
    text('generated/public/llms.txt'),
  ]);
  const freeEntry = registry.products.find(({ id }) => id === 'search').freeEntry;

  for (const [name, document] of [['skill.md', skill], ['agent.md', agent]]) {
    assert.ok(document.includes(registry.observedAt), `${name} must cite the registry observation time`);
    // Every reachable family appears; a family we do not offer is omitted rather
    // than published with the reason it is unavailable. Internal grading (proof
    // level, maturity, supplier-rights state) is not a caller fact.
    for (const product of registry.products) {
      const row = document.split('\n').find((line) => line.startsWith(`| ${product.label} |`));
      if (product.publiclyReachable) {
        assert.ok(row !== undefined, `${name} must list ${product.label}`);
        assert.ok(row.includes('available'), `${name}: ${product.label} row must state it is available`);
        assert.ok(!row.includes(product.proof), `${name}: ${product.label} row must not publish a proof level`);
      } else {
        assert.equal(row, undefined, `${name} must not list unoffered family ${product.label}`);
      }
    }
    assert.ok(!document.includes('packages/catalog/'), `${name} must not expose an internal source path`);
  }

  // The published command must match what the runtime actually accepts. While
  // the free route still requires a caller key the example carries one; once it
  // accepts a naive request the header disappears. A command that contradicts
  // the observed route would hand every first-time caller a 400.
  if (freeEntry !== null) {
    for (const [name, document] of [['skill.md', skill], ['agent.md', agent], ['llms.txt', llms]]) {
      assert.ok(document.includes(freeEntry.route), `${name} must publish the observed free route`);
      assert.equal(
        document.includes('idempotency-key:'),
        !freeEntry.acceptsNaiveRequest,
        `${name} must show an idempotency-key header exactly when the observed route requires one`,
      );
    }
    assert.ok(agent.includes(`Accepts a request with no idempotency key: ${freeEntry.acceptsNaiveRequest ? 'yes' : 'no'}`));
  }

  // An agent that reads the discovery document must be able to find them
  // without guessing a filename.
  const discovery = await json('generated/public/.well-known/clervo.json');
  assert.equal(discovery.artifacts.skill, '/skill.md');
  assert.equal(discovery.artifacts.agent, '/agent.md');
});

test('the API edge serves byte-identical copies of the two agent documents', async () => {
  // The Worker has no filesystem, so the documents are compiled into a module.
  // Two hosts serving two versions of the same document is the drift this
  // guards against.
  const [{ SKILL_DOCUMENT, AGENT_DOCUMENT }, skill, agent] = await Promise.all([
    import('../../generated/worker/agent-documents.js'),
    text('generated/public/skill.md'),
    text('generated/public/agent.md'),
  ]);
  assert.equal(SKILL_DOCUMENT, skill);
  assert.equal(AGENT_DOCUMENT, agent);
});

test('this suite pins no status value', async () => {
  // Rule 2: never assert that a product is in a particular lifecycle state.
  // Comparing a rendered surface against the registry is fine, and so is
  // deriving from a state inside a predicate; naming a state as the value a
  // surface is expected to have is what previously made honesty break the
  // build. This guard looks for a status literal in expected-value position.
  const source = await text('tests/contract/registry-public-consistency.test.mjs');
  const states = [...LIFECYCLE_STATES].join('|');
  const offenders = source
    .split('\n')
    .filter((line) => line.trimStart().startsWith('assert.'))
    .filter((line) => new RegExp(`,\\s*'(?:${states})'`, 'u').test(line));
  assert.deepEqual(offenders, [], 'an assertion pins a lifecycle state as an expected value');
});
